export const productFormData = {
  productName: "",
  sku: "", // auto-generated by pre("validate") if empty
  price: {
    current: "",
    original: "",
    currency: "₹"
  },
  category: "",       // Category _id
  subCategory: "",
  brand: "",
  offer: "",
  description: [],   // can be multiple
  features: [],      // can be multiple
  additionalInfo: [],
  images: [],        // image URLs
  isTrending: false,
  variations: []
};
export const variationFormData = {
  type: "",
  value: "",
  price: 0,
  stock: 0,
  image: null
};

export const categoryFormData={
  categoryName:"",
  subcategories:[]
}
export const comingSoonFormData={
  title:"",
  image:"",isActive:false
}
export const bannerFormData={
  title:"",
  image:"",isActive:false
}

export const SliderData = {
  title: "",
  subtitle: "",     
  description: "",  
  image: "",        
  isActive: true    
};