// Product form data (frontend)
export const productFormData = {
  productName: "",
  sku: "",           // auto-generated by pre("validate") if empty
  category: "",      // plain string
  subCategory: "",   // plain string
  brand: "",         
  description: [],   // multiple strings
  features: [],      // multiple strings
  additionalInfo: [], 
  images: [],        // array of image URLs
  isTrending: false, 
  variations: []     // array of variations
};

// Variation form data (frontend)
export const variationFormData = {
  type: "",          // e.g., "color", "size"
  value: "",         // e.g., "Red", "XL"
  price: {
    current: 0,
    original: 0,
    currency: "₹"
  },
  offer: 0,          // variation-specific offer
  stock: 0,
  image: null        // file or URL
};

export const categoryFormData={
  categoryName:"",
  subcategories:[]
}
export const comingSoonFormData={
  title:"",
  image:"",isActive:false
}
export const bannerFormData={
  title:"",
  image:"",isActive:false
}

export const SliderData = {
  title: "",
  subtitle: "",     
  description: "",  
  image: "",        
  isActive: true    
};

export const addressFormData = {
  // Identification
  title: "",         // e.g., "Home", "Work"
  userId: "",        // The ObjectId of the user (as a string)
  
  // Physical Location
  address: "",       // Street address
  city: "",
  pincode: "",       // Postal/ZIP code
  
  // Contact
  phone: "",
};